name: "build"

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.2', '7.3', '7.4', '8.0', '8.1']

            fail-fast: false

        name: PHP ${{ matrix.php }} Tests

        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: json, mbstring, xml, tokenizer, curl
                  coverage: none

            - run: composer install
            - run: composer ci
